grails-app/domain/com/omnitech/mis/Branch.groovy
package com.omnitech.mis

/**
 * Branch
 * A domain class describes the data object and it's mapping to the database
 */
class Branch {

    String id
    String branchName
    String location
    Date	dateCreated
    Date	lastUpdated

//	static	belongsTo	= []	// tells GORM to cascade commands: e.g., delete this object if the "parent" is deleted.
//	static	hasOne		= []	// tells GORM to associate another domain object as an owner in a 1-1 mapping
	static	hasMany		= [users:User]	// tells GORM to associate other domain objects for a 1-n or n-m mapping
//	static	mappedBy	= []	// specifies which property should be used in a mapping

    static	mapping = {
        id(generator: "com.omnitech.mis.utils.MyIdGenerator", type: "string", length: 32)
    }

    static	constraints = {
        branchName nullable: false
        location nullable: true
    }

    /*
     * Methods of the Domain Class
     */
    @Override	// Override toString for a nicer / more descriptive UI
    public String toString() {
        return "${branchName}";
    }
}

grails-app/controllers/com/omnitech/mis/BranchController.groovy
package com.omnitech.mis



import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
class BranchController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 100, 100)
        respond Branch.list(params), model:[branchInstanceCount: Branch.count()]
    }

    def show(Branch branchInstance) {
        respond branchInstance
    }

    def create() {
        respond new Branch(params)
    }

    @Transactional
    def save(Branch branchInstance) {
        if (branchInstance == null) {
            notFound()
            return
        }

        if (branchInstance.hasErrors()) {
            respond branchInstance.errors, view:'create'
            return
        }

        branchInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'branch.label', default: 'Branch'), branchInstance.branchName])
                redirect branchInstance
            }
            '*' { respond branchInstance, [status: CREATED] }
        }
    }

    def edit(Branch branchInstance) {
        respond branchInstance
    }

    @Transactional
    def update(Branch branchInstance) {
        if (branchInstance == null) {
            notFound()
            return
        }

        if (branchInstance.hasErrors()) {
            respond branchInstance.errors, view:'edit'
            return
        }

        branchInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'Branch.label', default: 'Branch'), branchInstance.branchName])
                redirect branchInstance
            }
            '*'{ respond branchInstance, [status: OK] }
        }
    }

    @Transactional
    def delete(Branch branchInstance) {

        if (branchInstance == null) {
            notFound()
            return
        }

        branchInstance.delete flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'Branch.label', default: 'Branch'), branchInstance.id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'branch.label', default: 'Branch'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails-app/views/branch/_form.gsp
<%@ page import="com.omnitech.mis.Branch" %>



<div class="${hasErrors(bean: branchInstance, field: 'branchName', 'error')} ">
	<label for="branchName" class="control-label"><g:message code="branch.branchName.label" default="Branch Name" /></label>
	<div>
		<g:textField class="form-control" style="width: 50%;"  name="branchName" value="${branchInstance?.branchName}"/>
		<span class="help-inline">${hasErrors(bean: branchInstance, field: 'branchName', 'error')}</span>
	</div>
</div>

<div class="${hasErrors(bean: branchInstance, field: 'location', 'error')} ">
	<label for="location" class="control-label"><g:message code="branch.location.label" default="District" /></label>
	<div>
		<g:textField  id="location" class="form-control" style="width: 50%;"  name="location" value="${branchInstance?.location}"/>
		<span class="help-inline">${hasErrors(bean: branchInstance, field: 'location', 'error')}</span>
	</div>
</div>

<div class="${hasErrors(bean: branchInstance, field: 'users', 'error')} ">
	<label for="users" class="control-label"><g:message code="branch.users.label" default="Users" /></label>
	<div>
		<g:select class="form-control chzn-select" style="width: 50%;" name="users" from="${com.omnitech.mis.User.list()}" multiple="multiple" optionKey="id" size="5" value="${branchInstance?.users*.id}"/>
		<span class="help-inline">${hasErrors(bean: branchInstance, field: 'users', 'error')}</span>
	</div>
</div>

grails-app/views/branch/create.gsp
<%@ page import="com.omnitech.mis.Branch" %>
<!DOCTYPE html>
<html>

<head>
	<meta name="layout" content="kickstart" />
	<g:set var="entityName" value="${message(code: 'branch.label', default: 'Branch')}" />
	<title><g:message code="default.create.label" args="[entityName]" /></title>
	<script src="${resource(dir: 'js/lib',file: 'jquery.autocomplete.js')}"></script>
	<script src="${resource(file: 'districts.js')}"></script>
	<script>
        $(document).ready(function () {
            var districtsArray = [];
            for (var i = 0; i < districts.length; i++) {
                districtsArray[i] = {value: districts[i].district, data: districts[i].region};
            }
            $("#location").autocomplete({
                source: districtsArray
            });
        });
	</script>
</head>

<body>

<section id="create-branch" class="first">

	<g:hasErrors bean="${branchInstance}">
		<div class="alert alert-danger">
			<g:renderErrors bean="${branchInstance}" as="list" />
		</div>
	</g:hasErrors>

	<g:form action="save" class="form-horizontal" role="form" >
	<g:render template="form"/>

	<div class="form-actions margin-top-medium">
		<g:submitButton name="create" class="btn btn-primary" value="${message(code: 'default.button.create.label', default: 'Create')}" />
		<button class="btn" type="reset"><g:message code="default.button.reset.label" default="Reset" /></button>
	</div>
	</g:form>

</section>

<r:require modules="chosen"/>
<g:javascript >
	$(".chzn-select").chosen();
</g:javascript>
</body>

</html>

grails-app/views/branch/edit.gsp
<%@ page import="com.omnitech.mis.Branch" %>
<!DOCTYPE html>
<html>

<head>
	<meta name="layout" content="kickstart" />
	<g:set var="entityName" value="${message(code: 'branch.label', default: 'Branch')}" />
	<title><g:message code="default.edit.label" args="[entityName]" /></title>
</head>

<body>

<section id="edit-branch" class="first">

	<g:hasErrors bean="${branchInstance}">
		<div class="alert alert-danger">
			<g:renderErrors bean="${branchInstance}" as="list" />
		</div>
	</g:hasErrors>

	<g:form method="post" class="form-horizontal" role="form" >
	<g:hiddenField name="id" value="${branchInstance?.id}" />
	<g:hiddenField name="version" value="${branchInstance?.version}" />
	<g:hiddenField name="_method" value="PUT" />

	<g:render template="form"/>

	<div class="form-actions margin-top-medium">
		<g:actionSubmit class="btn btn-primary" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
		<button class="btn" type="reset"><g:message code="default.button.reset.label" default="Reset" /></button>
	</div>
	</g:form>

</section>

<r:require modules="chosen"/>
<g:javascript >
	$(".chzn-select").chosen();
</g:javascript>
</body>

</html>

grails-app/views/branch/index.gsp
<%@ page import="com.omnitech.mis.Branch" %>
<!DOCTYPE html>
<html>

<head>
	<meta name="layout" content="kickstart" />
	<g:set var="entityName" value="${message(code: 'branch.label', default: 'Branch')}" />
	<title><g:message code="default.index.label" args="[entityName]" /></title>
</head>

<body>

<section id="index-branch" class="first">

	<table class="table table-bordered margin-top-medium">
		<thead>
		<tr>
			
			<g:sortableColumn property="branchName" title="${message(code: 'branch.branchName.label', default: 'Branch Name')}" />
			
			<g:sortableColumn property="location" title="${message(code: 'branch.location.label', default: 'Location')}" />
			
			<g:sortableColumn property="dateCreated" title="${message(code: 'branch.dateCreated.label', default: 'Date Created')}" />
			
			<g:sortableColumn property="lastUpdated" title="${message(code: 'branch.lastUpdated.label', default: 'Last Updated')}" />
			
			<td>
				Action
			</td>
		</tr>
		</thead>
		<tbody>
		<g:each in="${branchInstanceList}" status="i" var="branchInstance">
			<tr class="${(i % 2) == 0 ? 'odd' : 'even'}">
				
				<td><g:link action="show" id="${branchInstance.id}">${fieldValue(bean: branchInstance, field: "branchName")}</g:link></td>
				
				<td>${fieldValue(bean: branchInstance, field: "location")}</td>
				
				<td><g:formatDate date="${branchInstance.dateCreated}" format="dd-MMM-yyyy" /></td>
				
				<td><g:formatDate date="${branchInstance.lastUpdated}" format="dd-MMM-yyyy" /></td>
				
				<td>
					<g:link action="edit" id="${branchInstance.id}"><i
							class="glyphicon glyphicon-pencil"></i></g:link>

					<a href="#deleteModal" role="button"
					   class="delete-btnz btn-delete"
					   data-target="#deleteModal"
					   data-delete-id="${branchInstance?.id}"
					   data-toggle="modal"
					   data-field-name=" Are you sure you want to delete ${branchInstance?.branchName}"
					   data-field-title="Delete Branch"
					   title="Delete Branch">
						<i class="glyphicon glyphicon-remove"></i>
					</a>
				</td>
			</tr>
		</g:each>
		</tbody>
	</table>
	<div>
		<bs:paginate total="${branchInstanceCount}" />
	</div>
	<g:render template="/_common/modals/deleteDialog"/>
</section>

</body>

</html>

grails-app/views/branch/show.gsp
<%@ page import="com.omnitech.mis.Branch" %>
<!DOCTYPE html>
<html>

<head>
	<meta name="layout" content="kickstart" />
	<g:set var="entityName" value="${message(code: 'branch.label', default: 'Branch')}" />
	<title><g:message code="default.show.label" args="[entityName]" /></title>
</head>

<body>

<section id="show-branch" class="first">

	<table class="table">
		<tbody>
		
		<tr class="prop">
			<td valign="top" class="name"><g:message code="branch.branchName.label" default="Branch Name" /></td>
			
			<td valign="top" class="value">${fieldValue(bean: branchInstance, field: "branchName")}</td>
			
		</tr>
		
		<tr class="prop">
			<td valign="top" class="name"><g:message code="branch.location.label" default="Location" /></td>
			
			<td valign="top" class="value">${fieldValue(bean: branchInstance, field: "location")}</td>
			
		</tr>

		
		<tr class="prop">
			<td valign="top" class="name"><g:message code="branch.dateCreated.label" default="Date Created" /></td>
			
			<td valign="top" class="value"><g:formatDate date="${branchInstance?.dateCreated}" /></td>
			
		</tr>
		
		<tr class="prop">
			<td valign="top" class="name"><g:message code="branch.lastUpdated.label" default="Last Updated" /></td>
			
			<td valign="top" class="value"><g:formatDate date="${branchInstance?.lastUpdated}" /></td>
			
		</tr>
		
		<tr class="prop">
			<td valign="top" class="name"><g:message code="branch.users.label" default="Users" /></td>
			
			<td valign="top" style="text-align: left;" class="value">
				<ul>
					<g:each in="${branchInstance.users}" var="u">
						<li><g:link controller="user" action="show" id="${u.id}">${u?.encodeAsHTML()}</g:link></li>
					</g:each>
				</ul>
			</td>
			
		</tr>
		
		</tbody>
	</table>
</section>

</body>

</html>