grails-app/domain/com/omnitech/mis/LogVideoPlayback.groovy
package com.omnitech.mis

import org.grails.databinding.BindingFormat

/**
 * LogVideoPlayback
 * A domain class describes the data object and it's mapping to the database
 */
class LogVideoPlayback {

    /* Default (injected) attributes of GORM */
    String id
    String userId
    String username
    String videoTitle
    String videoUUID
    String sessionId
    String actionEvent
    Long currentTimeInSeconds
    Date timePlayed
//	Long	version

    /* Automatic timestamping of GORM */
    Date	dateCreated
    Date	lastUpdated

//	static	belongsTo	= []	// tells GORM to cascade commands: e.g., delete this object if the "parent" is deleted.
//	static	hasOne		= []	// tells GORM to associate another domain object as an owner in a 1-1 mapping
//	static	hasMany		= []	// tells GORM to associate other domain objects for a 1-n or n-m mapping
//	static	mappedBy	= []	// specifies which property should be used in a mapping

    static	mapping = {
        id generator: 'assigned'
        userId index: 'LogVideoPlayback_userid_idx'
        username index: 'LogVideoPlayback_username_idx'
        videoTitle index: 'LogVideoPlayback_video_title_idx'
        videoUUID index: "LogVideoPlayback_video_uuid_idx"
        sessionId index: 'LogVideoPlayback_sessionid_idx'
        actionEvent index: 'LogVideoPlayback_action_event_idx'
    }

    static	constraints = {
        userId nullable: false
        username nullable: false
        videoTitle nullable: false
        videoUUID nullable: false
        sessionId nullable: false
        actionEvent nullable: false
    }

    /*
     * Methods of the Domain Class
     */
    @Override	// Override toString for a nicer / more descriptive UI
    String toString() {
        return "${videoTitle}"
    }
}

grails-app/controllers/com/omnitech/mis/LogVideoPlaybackController.groovy
package com.omnitech.mis



import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
class LogVideoPlaybackController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 100, 100)
        params.sort = 'dateCreated'
        params.order = 'desc'
        respond LogVideoPlayback.list(params), model:[logVideoPlaybackInstanceCount: LogVideoPlayback.count()]
    }

    def show(LogVideoPlayback logVideoPlaybackInstance) {
        respond logVideoPlaybackInstance
    }

    def create() {
        respond new LogVideoPlayback(params)
    }

    @Transactional
    def save(LogVideoPlayback logVideoPlaybackInstance) {
        if (logVideoPlaybackInstance == null) {
            notFound()
            return
        }

        if (logVideoPlaybackInstance.hasErrors()) {
            respond logVideoPlaybackInstance.errors, view:'create'
            return
        }

        logVideoPlaybackInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'logVideoPlayback.label', default: 'LogVideoPlayback'), logVideoPlaybackInstance.id])
                redirect logVideoPlaybackInstance
            }
            '*' { respond logVideoPlaybackInstance, [status: CREATED] }
        }
    }

    def edit(LogVideoPlayback logVideoPlaybackInstance) {
        respond logVideoPlaybackInstance
    }

    @Transactional
    def update(LogVideoPlayback logVideoPlaybackInstance) {
        if (logVideoPlaybackInstance == null) {
            notFound()
            return
        }

        if (logVideoPlaybackInstance.hasErrors()) {
            respond logVideoPlaybackInstance.errors, view:'edit'
            return
        }

        logVideoPlaybackInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'LogVideoPlayback.label', default: 'LogVideoPlayback'), logVideoPlaybackInstance.id])
                redirect logVideoPlaybackInstance
            }
            '*'{ respond logVideoPlaybackInstance, [status: OK] }
        }
    }

    @Transactional
    def delete(LogVideoPlayback logVideoPlaybackInstance) {

        if (logVideoPlaybackInstance == null) {
            notFound()
            return
        }

        logVideoPlaybackInstance.delete flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'LogVideoPlayback.label', default: 'LogVideoPlayback'), logVideoPlaybackInstance.id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'logVideoPlayback.label', default: 'LogVideoPlayback'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }

    def exportToCSV(){
        String query = """
            SELECT lv.username,u.`name`,u.lg_uuid as mm_uid,lv.video_title,lv.date_created,lv.action_event,lv.current_time_in_seconds,
            lv.time_played FROM log_video_playback lv
            INNER JOIN `user` u on lv.username = u.username 
        """
        DataExporter.exportToCsvByQuery("LogvideoPlayback.csv",query.toString(),response,request)
    }
}

grails-app/views/logVideoPlayback/_form.gsp
<%@ page import="com.omnitech.mis.LogVideoPlayback" %>



<div class="${hasErrors(bean: logVideoPlaybackInstance, field: 'userId', 'error')} ">
	<label for="userId" class="control-label"><g:message code="logVideoPlayback.userId.label" default="User Id" /></label>
	<div>
		<g:textField class="form-control" name="userId" value="${logVideoPlaybackInstance?.userId}"/>
		<span class="help-inline">${hasErrors(bean: logVideoPlaybackInstance, field: 'userId', 'error')}</span>
	</div>
</div>

<div class="${hasErrors(bean: logVideoPlaybackInstance, field: 'username', 'error')} ">
	<label for="username" class="control-label"><g:message code="logVideoPlayback.username.label" default="Username" /></label>
	<div>
		<g:textField class="form-control" name="username" value="${logVideoPlaybackInstance?.username}"/>
		<span class="help-inline">${hasErrors(bean: logVideoPlaybackInstance, field: 'username', 'error')}</span>
	</div>
</div>

<div class="${hasErrors(bean: logVideoPlaybackInstance, field: 'videoTitle', 'error')} ">
	<label for="videoTitle" class="control-label"><g:message code="logVideoPlayback.videoTitle.label" default="Video Title" /></label>
	<div>
		<g:textField class="form-control" name="videoTitle" value="${logVideoPlaybackInstance?.videoTitle}"/>
		<span class="help-inline">${hasErrors(bean: logVideoPlaybackInstance, field: 'videoTitle', 'error')}</span>
	</div>
</div>

<div class="${hasErrors(bean: logVideoPlaybackInstance, field: 'videoUUID', 'error')} ">
	<label for="videoUUID" class="control-label"><g:message code="logVideoPlayback.videoUUID.label" default="Video UUID" /></label>
	<div>
		<g:textField class="form-control" name="videoUUID" value="${logVideoPlaybackInstance?.videoUUID}"/>
		<span class="help-inline">${hasErrors(bean: logVideoPlaybackInstance, field: 'videoUUID', 'error')}</span>
	</div>
</div>

<div class="${hasErrors(bean: logVideoPlaybackInstance, field: 'sessionId', 'error')} ">
	<label for="sessionId" class="control-label"><g:message code="logVideoPlayback.sessionId.label" default="Session Id" /></label>
	<div>
		<g:textField class="form-control" name="sessionId" value="${logVideoPlaybackInstance?.sessionId}"/>
		<span class="help-inline">${hasErrors(bean: logVideoPlaybackInstance, field: 'sessionId', 'error')}</span>
	</div>
</div>

<div class="${hasErrors(bean: logVideoPlaybackInstance, field: 'actionEvent', 'error')} ">
	<label for="actionEvent" class="control-label"><g:message code="logVideoPlayback.actionEvent.label" default="Action Event" /></label>
	<div>
		<g:textField class="form-control" name="actionEvent" value="${logVideoPlaybackInstance?.actionEvent}"/>
		<span class="help-inline">${hasErrors(bean: logVideoPlaybackInstance, field: 'actionEvent', 'error')}</span>
	</div>
</div>

<div class="${hasErrors(bean: logVideoPlaybackInstance, field: 'currentTimeInSeconds', 'error')} required">
	<label for="currentTimeInSeconds" class="control-label"><g:message code="logVideoPlayback.currentTimeInSeconds.label" default="Current Time In Seconds" /><span class="required-indicator">*</span></label>
	<div>
		<g:field class="form-control" style="width: 50%;" name="currentTimeInSeconds" type="number" value="${logVideoPlaybackInstance.currentTimeInSeconds}" required=""/>
		<span class="help-inline">${hasErrors(bean: logVideoPlaybackInstance, field: 'currentTimeInSeconds', 'error')}</span>
	</div>
</div>

grails-app/views/logVideoPlayback/create.gsp
<%@ page import="com.omnitech.mis.LogVideoPlayback" %>
<!DOCTYPE html>
<html>

<head>
	<meta name="layout" content="kickstart" />
	<g:set var="entityName" value="${message(code: 'logVideoPlayback.label', default: 'LogVideoPlayback')}" />
	<title><g:message code="default.create.label" args="[entityName]" /></title>
</head>

<body>

<section id="create-logVideoPlayback" class="first">

	<g:hasErrors bean="${logVideoPlaybackInstance}">
		<div class="alert alert-danger">
			<g:renderErrors bean="${logVideoPlaybackInstance}" as="list" />
		</div>
	</g:hasErrors>

	<g:form action="save" class="form-horizontal" role="form" >
	<g:render template="form"/>

	<div class="form-actions margin-top-medium">
		<g:submitButton name="create" class="btn btn-primary" value="${message(code: 'default.button.create.label', default: 'Create')}" />
		<button class="btn" type="reset"><g:message code="default.button.reset.label" default="Reset" /></button>
	</div>
	</g:form>

</section>

</body>

</html>

grails-app/views/logVideoPlayback/edit.gsp
<%@ page import="com.omnitech.mis.LogVideoPlayback" %>
<!DOCTYPE html>
<html>

<head>
	<meta name="layout" content="kickstart" />
	<g:set var="entityName" value="${message(code: 'logVideoPlayback.label', default: 'LogVideoPlayback')}" />
	<title><g:message code="default.edit.label" args="[entityName]" /></title>
</head>

<body>

<section id="edit-logVideoPlayback" class="first">

	<g:hasErrors bean="${logVideoPlaybackInstance}">
		<div class="alert alert-danger">
			<g:renderErrors bean="${logVideoPlaybackInstance}" as="list" />
		</div>
	</g:hasErrors>

	<g:form method="post" class="form-horizontal" role="form" >
	<g:hiddenField name="id" value="${logVideoPlaybackInstance?.id}" />
	<g:hiddenField name="version" value="${logVideoPlaybackInstance?.version}" />
	<g:hiddenField name="_method" value="PUT" />

	<g:render template="form"/>

	<div class="form-actions margin-top-medium">
		<g:actionSubmit class="btn btn-primary" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
		<button class="btn" type="reset"><g:message code="default.button.reset.label" default="Reset" /></button>
	</div>
	</g:form>

</section>

</body>

</html>

grails-app/views/logVideoPlayback/index.gsp
<%@ page import="com.omnitech.mis.LogVideoPlayback" %>
<!DOCTYPE html>
<html>

<head>
	<meta name="layout" content="kickstart" />
	<g:set var="entityName" value="${message(code: 'logVideoPlayback.label', default: 'LogVideoPlayback')}" />
	<title><g:message code="default.index.label" args="[entityName]" /></title>
	<g:set var="layout_nojambotron" value="true" scope="request"/>
</head>

<body>

<section id="index-logVideoPlayback" class="first">

	<table class="table table-bordered margin-top-medium">
		<thead>
		<tr>

			<g:sortableColumn property="username" title="${message(code: 'logVideoPlayback.username.label', default: 'Username')}" />
			
			<g:sortableColumn property="videoTitle" title="${message(code: 'logVideoPlayback.videoTitle.label', default: 'Video Title')}" />

			<g:sortableColumn property="currentTimeInSeconds" title="${message(code: 'logVideoPlayback.actionEvent.label', default: 'Position in Video(Seconds)')}" />
			
			<g:sortableColumn property="dateCreated" title="${message(code: 'logVideoPlayback.videoUUID.label', default: 'Date Uploaded')}" />
			
			<g:sortableColumn property="timePlayed" title="${message(code: 'logVideoPlayback.sessionId.label', default: 'Time Of Action')}" />

			<g:sortableColumn property="sessionId" title="${message(code: 'logVideoPlayback.sessionId.label', default: 'Session')}" />
			
			<g:sortableColumn property="actionEvent" title="${message(code: 'logVideoPlayback.actionEvent.label', default: 'Action Event')}" />

			<td>
				Action
			</td>
		</tr>
		</thead>
		<tbody>
		<g:each in="${logVideoPlaybackInstanceList}" status="i" var="logVideoPlaybackInstance">
			<tr class="${(i % 2) == 0 ? 'odd' : 'even'}">
				
				<td>
					${(params.offset ? (params.offset as Long) + 1 : 1) + i}.
					<g:link action="show" id="${logVideoPlaybackInstance.id}">${fieldValue(bean: logVideoPlaybackInstance, field: "username")}</g:link></td>

				<td>${fieldValue(bean: logVideoPlaybackInstance, field: "videoTitle")}</td>

				<td>${fieldValue(bean: logVideoPlaybackInstance, field: "currentTimeInSeconds")}</td>
				
				<td><g:formatDate date="${logVideoPlaybackInstance.dateCreated}" format="dd-MMM-yyyy hh:mm ss" /></td>
				
				<td><g:formatDate date="${logVideoPlaybackInstance.timePlayed}" format="dd-MMM-yyyy hh:mm ss" /></td>

				<td>${fieldValue(bean: logVideoPlaybackInstance, field: "sessionId")}</td>
				
				<td>${fieldValue(bean: logVideoPlaybackInstance, field: "actionEvent")}</td>
				
				<td>
					<g:link action="edit" id="${logVideoPlaybackInstance.id}"><i
							class="glyphicon glyphicon-pencil"></i></g:link>
					<g:link action="delete" id="${logVideoPlaybackInstance.id}"><i
							class="glyphicon glyphicon-remove"></i></g:link>
				</td>
			</tr>
		</g:each>
		</tbody>
	</table>
	<div>
		<bs:paginate total="${logVideoPlaybackInstanceCount}" />
	</div>
</section>

</body>

</html>

grails-app/views/logVideoPlayback/show.gsp
<%@ page import="com.omnitech.mis.LogVideoPlayback" %>
<!DOCTYPE html>
<html>

<head>
	<meta name="layout" content="kickstart" />
	<g:set var="entityName" value="${message(code: 'logVideoPlayback.label', default: 'LogVideoPlayback')}" />
	<title><g:message code="default.show.label" args="[entityName]" /></title>
</head>

<body>

<section id="show-logVideoPlayback" class="first">

	<table class="table">
		<tbody>
		
		<tr class="prop">
			<td valign="top" class="name"><g:message code="logVideoPlayback.userId.label" default="User Id" /></td>
			
			<td valign="top" class="value">${fieldValue(bean: logVideoPlaybackInstance, field: "userId")}</td>
			
		</tr>
		
		<tr class="prop">
			<td valign="top" class="name"><g:message code="logVideoPlayback.username.label" default="Username" /></td>
			
			<td valign="top" class="value">${fieldValue(bean: logVideoPlaybackInstance, field: "username")}</td>
			
		</tr>
		
		<tr class="prop">
			<td valign="top" class="name"><g:message code="logVideoPlayback.videoTitle.label" default="Video Title" /></td>
			
			<td valign="top" class="value">${fieldValue(bean: logVideoPlaybackInstance, field: "videoTitle")}</td>
			
		</tr>
		
		<tr class="prop">
			<td valign="top" class="name"><g:message code="logVideoPlayback.videoUUID.label" default="Video UUID" /></td>
			
			<td valign="top" class="value">${fieldValue(bean: logVideoPlaybackInstance, field: "videoUUID")}</td>
			
		</tr>
		
		<tr class="prop">
			<td valign="top" class="name"><g:message code="logVideoPlayback.sessionId.label" default="Session Id" /></td>
			
			<td valign="top" class="value">${fieldValue(bean: logVideoPlaybackInstance, field: "sessionId")}</td>
			
		</tr>
		
		<tr class="prop">
			<td valign="top" class="name"><g:message code="logVideoPlayback.actionEvent.label" default="Action Event" /></td>
			
			<td valign="top" class="value">${fieldValue(bean: logVideoPlaybackInstance, field: "actionEvent")}</td>
			
		</tr>
		
		<tr class="prop">
			<td valign="top" class="name"><g:message code="logVideoPlayback.currentTimeInSeconds.label" default="Current Time In Seconds" /></td>
			
			<td valign="top" class="value">${fieldValue(bean: logVideoPlaybackInstance, field: "currentTimeInSeconds")}</td>
			
		</tr>
		
		<tr class="prop">
			<td valign="top" class="name"><g:message code="logVideoPlayback.dateCreated.label" default="Date Created" /></td>
			
			<td valign="top" class="value"><g:formatDate date="${logVideoPlaybackInstance?.dateCreated}" /></td>
			
		</tr>
		
		<tr class="prop">
			<td valign="top" class="name"><g:message code="logVideoPlayback.lastUpdated.label" default="Last Updated" /></td>
			
			<td valign="top" class="value"><g:formatDate date="${logVideoPlaybackInstance?.lastUpdated}" /></td>
			
		</tr>
		
		</tbody>
	</table>
</section>

</body>

</html>