grails-app/domain/com/omnitech/mis/District.groovy
package com.omnitech.mis

/**
 * District
 */
class District {

    String id
    String name
    Date dateCreated
    Date lastUpdated

    static auditable = true

    static hasMany = [subcounties:SubCounty]

    static mapping = {
        id(generator: "com.omnitech.mis.utils.MyIdGenerator", type: "string", length: 32)
    }

    static constraints = {
        name blank: false
    }

    /*
     * Methods of the Domain Class
     */

    @Override    // Override toString for a nicer / more descriptive UI
    public String toString() {
        return "${name}";
    }
}

grails-app/controllers/com/omnitech/mis/DistrictController.groovy
package com.omnitech.mis


import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

/**
 * DistrictController
 * A controller class handles incoming web requests and performs actions such as redirects, rendering views and so on.
 */
@Transactional(readOnly = true)
class DistrictController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

	def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond District.list(params), model:[districtInstanceCount: District.count()]
    }

	def list(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond District.list(params), model:[districtInstanceCount: District.count()]
    }

    def show(District districtInstance) {
        respond districtInstance
    }

    def create() {
        respond new District(params)
    }

    @Transactional
    def save(District districtInstance) {
        if (districtInstance == null) {
            notFound()
            return
        }

        if (districtInstance.hasErrors()) {
            respond districtInstance.errors, view:'create'
            return
        }

        districtInstance.save flush:true

        request.withFormat {
            form {
                flash.message = message(code: 'default.created.message', args: [message(code: 'districtInstance.label', default: 'District'), districtInstance.id])
                redirect districtInstance
            }
            '*' { respond districtInstance, [status: CREATED] }
        }
    }

    def edit(District districtInstance) {
        respond districtInstance
    }

    @Transactional
    def update(District districtInstance) {
        if (districtInstance == null) {
            notFound()
            return
        }

        if (districtInstance.hasErrors()) {
            respond districtInstance.errors, view:'edit'
            return
        }

        districtInstance.save flush:true

        request.withFormat {
            form {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'District.label', default: 'District'), districtInstance.id])
                redirect districtInstance
            }
            '*'{ respond districtInstance, [status: OK] }
        }
    }

    @Transactional
    def delete(District districtInstance) {

        if (districtInstance == null) {
            notFound()
            return
        }

        districtInstance.delete flush:true

        request.withFormat {
            form {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'District.label', default: 'District'), districtInstance.id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'districtInstance.label', default: 'District'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails-app/views/district/_form.gsp
<%@ page import="com.omnitech.mis.District" %>



			<div class="${hasErrors(bean: districtInstance, field: 'name', 'error')} required">
				<label for="name" class="control-label"><g:message code="district.name.label" default="Name" /><span class="required-indicator">*</span></label>
				<div>
					<g:textField class="form-control" name="name" required="" value="${districtInstance?.name}"/>
					<span class="help-inline">${hasErrors(bean: districtInstance, field: 'name', 'error')}</span>
				</div>
			</div>

			<div class="${hasErrors(bean: districtInstance, field: 'subcounties', 'error')} ">
				<label for="subcounties" class="control-label"><g:message code="district.subcounties.label" default="Subcounties" /></label>
				<div>
					
<ul class="one-to-many">
<g:each in="${districtInstance?.subcounties?}" var="s">
    <li><g:link controller="subCounty" action="show" id="${s.id}">${s?.encodeAsHTML()}</g:link></li>
</g:each>
<li class="add">
<g:link controller="subCounty" action="create" params="['district.id': districtInstance?.id]">${message(code: 'default.add.label', args: [message(code: 'subCounty.label', default: 'SubCounty')])}</g:link>
</li>
</ul>

					<span class="help-inline">${hasErrors(bean: districtInstance, field: 'subcounties', 'error')}</span>
				</div>
			</div>

grails-app/views/district/create.gsp
<%@ page import="com.omnitech.mis.District" %>
<!DOCTYPE html>
<html>

<head>
	<meta name="layout" content="kickstart" />
	<g:set var="entityName" value="${message(code: 'district.label', default: 'District')}" />
	<title><g:message code="default.create.label" args="[entityName]" /></title>
</head>

<body>

	<section id="create-district" class="first">

		<g:hasErrors bean="${districtInstance}">
		<div class="alert alert-danger">
			<g:renderErrors bean="${districtInstance}" as="list" />
		</div>
		</g:hasErrors>

		<g:form action="save" class="form-horizontal" role="form" >
			<g:render template="form"/>

			<div class="form-actions margin-top-medium">
				<g:submitButton name="create" class="btn btn-primary" value="${message(code: 'default.button.create.label', default: 'Create')}" />
	            <button class="btn" type="reset"><g:message code="default.button.reset.label" default="Reset" /></button>
			</div>
		</g:form>

	</section>

</body>

</html>

grails-app/views/district/edit.gsp
<%@ page import="com.omnitech.mis.District" %>
<!DOCTYPE html>
<html>

<head>
	<meta name="layout" content="kickstart" />
	<g:set var="entityName" value="${message(code: 'district.label', default: 'District')}" />
	<title><g:message code="default.edit.label" args="[entityName]" /></title>
</head>

<body>

	<section id="edit-district" class="first">

		<g:hasErrors bean="${districtInstance}">
		<div class="alert alert-danger">
			<g:renderErrors bean="${districtInstance}" as="list" />
		</div>
		</g:hasErrors>

		<g:form method="post" class="form-horizontal" role="form" >
			<g:hiddenField name="id" value="${districtInstance?.id}" />
			<g:hiddenField name="version" value="${districtInstance?.version}" />
			<g:hiddenField name="_method" value="PUT" />
			
			<g:render template="form"/>
			
			<div class="form-actions margin-top-medium">
				<g:actionSubmit class="btn btn-primary" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
	            <button class="btn" type="reset"><g:message code="default.button.reset.label" default="Reset" /></button>
			</div>
		</g:form>

	</section>

</body>

</html>

grails-app/views/district/index.gsp
<%@ page import="com.omnitech.mis.District" %>
<!DOCTYPE html>
<html>

<head>
    <meta name="layout" content="kickstart" />
    <g:set var="entityName" value="${message(code: 'district.label', default: 'District')}" />
    <title><g:message code="default.index.label" args="[entityName]" /></title>
</head>

<body>

<section id="index-district" class="first">

    <table class="table table-bordered margin-top-medium">
        <thead>
        <tr>
            
            <g:sortableColumn property="name" title="${message(code: 'district.name.label', default: 'Name')}" />
            
            <g:sortableColumn property="dateCreated" title="${message(code: 'district.dateCreated.label', default: 'Date Created')}" />
            
            <g:sortableColumn property="lastUpdated" title="${message(code: 'district.lastUpdated.label', default: 'Last Updated')}" />
            
            <td>
                Action
            </td>
        </tr>
        </thead>
        <tbody>
        <g:each in="${districtInstanceList}" status="i" var="districtInstance">
            <tr class="${(i % 2) == 0 ? 'odd' : 'even'}">
                
                <td><g:link action="show" id="${districtInstance.id}">${fieldValue(bean: districtInstance, field: "name")}</g:link></td>
                
                <td><g:formatDate date="${districtInstance.dateCreated}" format="dd-MMM-yyyy" /></td>
                
                <td><g:formatDate date="${districtInstance.lastUpdated}" format="dd-MMM-yyyy" /></td>
                
                <td>
                    <g:link action="edit" id="${districtInstance.id}"><i
                            class="glyphicon glyphicon-pencil"></i></g:link>


                    <a href="#deleteModal" role="button"
                       class="delete-btnz btn-delete"
                       data-target="#deleteModal"
                       data-delete-id="${districtInstance?.id}"
                       data-toggle="modal"
                       data-field-name=" Are you sure you want to delete ${districtInstance?.name}"
                       data-field-title="Delete District"
                       title="Delete District">
                        <i class="glyphicon glyphicon-remove"></i>
                    </a>
                </td>
            </tr>
        </g:each>
        </tbody>
    </table>
    <div>
        <bs:paginate total="${districtInstanceCount}" />
    </div>
    <g:render template="/_common/modals/deleteDialog"/>
</section>

</body>

</html>

grails-app/views/district/list.gsp
<%@ page import="com.omnitech.mis.District" %>
<!DOCTYPE html>
<html>

<head>
    <meta name="layout" content="kickstart"/>
    <g:set var="entityName" value="${message(code: 'district.label', default: 'District')}"/>
    <title><g:message code="default.list.label" args="[entityName]"/></title>
</head>

<body>

<section id="list-district" class="first">

    <table class="table table-bordered margin-top-medium">
        <thead>
        <tr>
            
            <g:sortableColumn property="name"
                              title="${message(code: 'district.name.label', default: 'Name')}"/>
            
            <g:sortableColumn property="dateCreated"
                              title="${message(code: 'district.dateCreated.label', default: 'Date Created')}"/>
            
            <g:sortableColumn property="lastUpdated"
                              title="${message(code: 'district.lastUpdated.label', default: 'Last Updated')}"/>
            
        </tr>
        </thead>
        <tbody>
        <g:each in="${districtInstanceList}" status="i" var="districtInstance">
            <tr class="${(i % 2) == 0 ? 'odd' : 'even'}">
                
                <td><g:link action="show"
                            id="${districtInstance.id}">${fieldValue(bean: districtInstance, field: "name")}</g:link></td>
                
                <td><g:formatDate date="${districtInstance.dateCreated}"/></td>
                
                <td><g:formatDate date="${districtInstance.lastUpdated}"/></td>
                
            </tr>
        </g:each>
        </tbody>
    </table>

    <div>
        <bs:paginate total="${districtInstanceCount}"/>
    </div>
</section>

</body>

</html>

grails-app/views/district/show.gsp
<%@ page import="com.omnitech.mis.District" %>
<!DOCTYPE html>
<html>

<head>
	<meta name="layout" content="kickstart" />
	<g:set var="entityName" value="${message(code: 'district.label', default: 'District')}" />
	<title><g:message code="default.show.label" args="[entityName]" /></title>
</head>

<body>

<section id="show-district" class="first">

	<table class="table">
		<tbody>
		
			<tr class="prop">
				<td valign="top" class="name"><g:message code="district.name.label" default="Name" /></td>
				
				<td valign="top" class="value">${fieldValue(bean: districtInstance, field: "name")}</td>
				
			</tr>
		
			<tr class="prop">
				<td valign="top" class="name"><g:message code="district.dateCreated.label" default="Date Created" /></td>
				
				<td valign="top" class="value"><g:formatDate date="${districtInstance?.dateCreated}" /></td>
				
			</tr>
		
			<tr class="prop">
				<td valign="top" class="name"><g:message code="district.lastUpdated.label" default="Last Updated" /></td>
				
				<td valign="top" class="value"><g:formatDate date="${districtInstance?.lastUpdated}" /></td>
				
			</tr>
		
			<tr class="prop">
				<td valign="top" class="name"><g:message code="district.subcounties.label" default="Subcounties" /></td>
				
				<td valign="top" style="text-align: left;" class="value">
					<ul>
					<g:each in="${districtInstance.subcounties}" var="s">
						<li><g:link controller="subCounty" action="show" id="${s.id}">${s?.encodeAsHTML()}</g:link></li>
					</g:each>
					</ul>
				</td>
				
			</tr>
		
		</tbody>
	</table>
</section>

</body>

</html>