grails-app/domain/com/omnitech/mis/ProductCategory.groovy
package com.omnitech.mis

/**
 * ProductCategory
 * A domain class describes the data object and it's mapping to the database
 */
class ProductCategory {

    String id
    String categoryName
    String description
    Date	dateCreated
    Date	lastUpdated

//	static	belongsTo	= []	// tells GORM to cascade commands: e.g., delete this object if the "parent" is deleted.
//	static	hasOne		= []	// tells GORM to associate another domain object as an owner in a 1-1 mapping
	static	hasMany		= [products:Product]	// tells GORM to associate other domain objects for a 1-n or n-m mapping
//	static	mappedBy	= []	// specifies which property should be used in a mapping

    static	mapping = {
        id(generator: "com.omnitech.mis.utils.MyIdGenerator", type: "string", length: 32)
    }

    static	constraints = {
        categoryName nullable: false
        description nullable: true
    }

    /*
     * Methods of the Domain Class
     */
    @Override	// Override toString for a nicer / more descriptive UI
    public String toString() {
        return "${categoryName}";
    }

    def userProducts(User user){
        return user.findProducts(this)
    }
}

grails-app/controllers/com/omnitech/mis/ProductCategoryController.groovy
package com.omnitech.mis



import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
class ProductCategoryController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 100, 100)
        respond ProductCategory.list(params), model:[productCategoryInstanceCount: ProductCategory.count()]
    }

    def show(ProductCategory productCategoryInstance) {
        respond productCategoryInstance
    }

    def create() {
        respond new ProductCategory(params)
    }

    @Transactional
    def save(ProductCategory productCategoryInstance) {
        if (productCategoryInstance == null) {
            notFound()
            return
        }

        if (productCategoryInstance.hasErrors()) {
            respond productCategoryInstance.errors, view:'create'
            return
        }

        productCategoryInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'productCategory.label', default: 'ProductCategory'), productCategoryInstance.categoryName])
                redirect productCategoryInstance
            }
            '*' { respond productCategoryInstance, [status: CREATED] }
        }
    }

    def edit(ProductCategory productCategoryInstance) {
        respond productCategoryInstance
    }

    @Transactional
    def update(ProductCategory productCategoryInstance) {
        if (productCategoryInstance == null) {
            notFound()
            return
        }

        if (productCategoryInstance.hasErrors()) {
            respond productCategoryInstance.errors, view:'edit'
            return
        }

        productCategoryInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'ProductCategory.label', default: 'ProductCategory'), productCategoryInstance.categoryName])
                redirect productCategoryInstance
            }
            '*'{ respond productCategoryInstance, [status: OK] }
        }
    }

    @Transactional
    def delete(ProductCategory productCategoryInstance) {

        if (productCategoryInstance == null) {
            notFound()
            return
        }

        productCategoryInstance.delete flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'ProductCategory.label', default: 'ProductCategory'), productCategoryInstance.categoryName])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'productCategory.label', default: 'ProductCategory'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails-app/views/productCategory/_form.gsp
<%@ page import="com.omnitech.mis.ProductCategory" %>



<div class="${hasErrors(bean: productCategoryInstance, field: 'categoryName', 'error')} ">
	<label for="categoryName" class="control-label"><g:message code="productCategory.categoryName.label" default="Category Name" /></label>
	<div>
		<g:textField class="form-control" name="categoryName" value="${productCategoryInstance?.categoryName}"/>
		<span class="help-inline">${hasErrors(bean: productCategoryInstance, field: 'categoryName', 'error')}</span>
	</div>
</div>

<div class="${hasErrors(bean: productCategoryInstance, field: 'description', 'error')} ">
	<label for="description" class="control-label"><g:message code="productCategory.description.label" default="Description" /></label>
	<div>
		<g:textField class="form-control" name="description" value="${productCategoryInstance?.description}"/>
		<span class="help-inline">${hasErrors(bean: productCategoryInstance, field: 'description', 'error')}</span>
	</div>
</div>

<div class="${hasErrors(bean: productCategoryInstance, field: 'products', 'error')} ">
	<label for="products" class="control-label"><g:message code="productCategory.products.label" default="Products" /></label>
	<div>
		
<ul class="one-to-many">
<g:each in="${productCategoryInstance?.products?}" var="p">
    <li><g:link controller="product" action="show" id="${p.id}">${p?.encodeAsHTML()}</g:link></li>
</g:each>
<li class="add">
<g:link controller="product" action="create" params="['productCategory.id': productCategoryInstance?.id]">${message(code: 'default.add.label', args: [message(code: 'product.label', default: 'Product')])}</g:link>
</li>
</ul>

		<span class="help-inline">${hasErrors(bean: productCategoryInstance, field: 'products', 'error')}</span>
	</div>
</div>

grails-app/views/productCategory/create.gsp
<%@ page import="com.omnitech.mis.ProductCategory" %>
<!DOCTYPE html>
<html>

<head>
	<meta name="layout" content="kickstart" />
	<g:set var="entityName" value="${message(code: 'productCategory.label', default: 'ProductCategory')}" />
	<title><g:message code="default.create.label" args="[entityName]" /></title>
</head>

<body>

<section id="create-productCategory" class="first">

	<g:hasErrors bean="${productCategoryInstance}">
		<div class="alert alert-danger">
			<g:renderErrors bean="${productCategoryInstance}" as="list" />
		</div>
	</g:hasErrors>

	<g:form action="save" class="form-horizontal" role="form" >
	<g:render template="form"/>

	<div class="form-actions margin-top-medium">
		<g:submitButton name="create" class="btn btn-primary" value="${message(code: 'default.button.create.label', default: 'Create')}" />
		<button class="btn" type="reset"><g:message code="default.button.reset.label" default="Reset" /></button>
	</div>
	</g:form>

</section>

</body>

</html>

grails-app/views/productCategory/edit.gsp
<%@ page import="com.omnitech.mis.ProductCategory" %>
<!DOCTYPE html>
<html>

<head>
	<meta name="layout" content="kickstart" />
	<g:set var="entityName" value="${message(code: 'productCategory.label', default: 'ProductCategory')}" />
	<title><g:message code="default.edit.label" args="[entityName]" /></title>
</head>

<body>

<section id="edit-productCategory" class="first">

	<g:hasErrors bean="${productCategoryInstance}">
		<div class="alert alert-danger">
			<g:renderErrors bean="${productCategoryInstance}" as="list" />
		</div>
	</g:hasErrors>

	<g:form method="post" class="form-horizontal" role="form" >
	<g:hiddenField name="id" value="${productCategoryInstance?.id}" />
	<g:hiddenField name="version" value="${productCategoryInstance?.version}" />
	<g:hiddenField name="_method" value="PUT" />

	<g:render template="form"/>

	<div class="form-actions margin-top-medium">
		<g:actionSubmit class="btn btn-primary" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
		<button class="btn" type="reset"><g:message code="default.button.reset.label" default="Reset" /></button>
	</div>
	</g:form>

</section>

</body>

</html>

grails-app/views/productCategory/index.gsp
<%@ page import="com.omnitech.mis.ProductCategory" %>
<!DOCTYPE html>
<html>

<head>
	<meta name="layout" content="kickstart" />
	<g:set var="entityName" value="${message(code: 'productCategory.label', default: 'ProductCategory')}" />
	<g:set var="layout_nojambotron" value="true" scope="request"/>
	<title><g:message code="default.index.label" args="[entityName]" /></title>
</head>

<body>

<section id="index-productCategory" class="first">

	<table class="table table-bordered margin-top-medium">
		<thead>
		<tr>
			
			<g:sortableColumn property="categoryName" title="${message(code: 'productCategory.categoryName.label', default: 'Category Name')}" />
			
			<g:sortableColumn property="description" title="${message(code: 'productCategory.description.label', default: 'Description')}" />
			
			<g:sortableColumn property="dateCreated" title="${message(code: 'productCategory.dateCreated.label', default: 'Date Created')}" />
			
			<g:sortableColumn property="lastUpdated" title="${message(code: 'productCategory.lastUpdated.label', default: 'Last Updated')}" />
			
			<td>
				Action
			</td>
		</tr>
		</thead>
		<tbody>
		<g:each in="${productCategoryInstanceList}" status="i" var="productCategoryInstance">
			<tr class="${(i % 2) == 0 ? 'odd' : 'even'}">
				
				<td><g:link action="show" id="${productCategoryInstance.id}">${fieldValue(bean: productCategoryInstance, field: "categoryName")}</g:link></td>
				
				<td>${fieldValue(bean: productCategoryInstance, field: "description")}</td>
				
				<td><g:formatDate date="${productCategoryInstance.dateCreated}" format="dd-MMM-yyyy" /></td>
				
				<td><g:formatDate date="${productCategoryInstance.lastUpdated}" format="dd-MMM-yyyy" /></td>
				
				<td>
					<g:link action="edit" id="${productCategoryInstance.id}"><i
							class="glyphicon glyphicon-pencil"></i></g:link>


					<a href="#deleteModal" role="button"
					   class="delete-btnz btn-delete"
					   data-target="#deleteModal"
					   data-delete-id="${productCategoryInstance?.id}"
					   data-toggle="modal"
					   data-field-name=" Are you sure you want to delete ${productCategoryInstance?.categoryName}"
					   data-field-title="Delete Category"
					   title="Delete Category">
						<i class="glyphicon glyphicon-remove"></i>
					</a>
				</td>
			</tr>
		</g:each>
		</tbody>
	</table>
	<div>
		<bs:paginate total="${productCategoryInstanceCount}" />
	</div>
	<g:render template="/_common/modals/deleteDialog"/>
</section>

</body>

</html>

grails-app/views/productCategory/show.gsp
<%@ page import="com.omnitech.mis.ProductCategory" %>
<!DOCTYPE html>
<html>

<head>
	<meta name="layout" content="kickstart" />
	<g:set var="entityName" value="${message(code: 'productCategory.label', default: 'ProductCategory')}" />
	<title><g:message code="default.show.label" args="[entityName]" /></title>
</head>

<body>

<section id="show-productCategory" class="first">

	<table class="table">
		<tbody>
		
		<tr class="prop">
			<td valign="top" class="name"><g:message code="productCategory.categoryName.label" default="Category Name" /></td>
			
			<td valign="top" class="value">${fieldValue(bean: productCategoryInstance, field: "categoryName")}</td>
			
		</tr>
		
		<tr class="prop">
			<td valign="top" class="name"><g:message code="productCategory.description.label" default="Description" /></td>
			
			<td valign="top" class="value">${fieldValue(bean: productCategoryInstance, field: "description")}</td>
			
		</tr>
		
		<tr class="prop">
			<td valign="top" class="name"><g:message code="productCategory.dateCreated.label" default="Date Created" /></td>
			
			<td valign="top" class="value"><g:formatDate date="${productCategoryInstance?.dateCreated}" /></td>
			
		</tr>
		
		<tr class="prop">
			<td valign="top" class="name"><g:message code="productCategory.lastUpdated.label" default="Last Updated" /></td>
			
			<td valign="top" class="value"><g:formatDate date="${productCategoryInstance?.lastUpdated}" /></td>
			
		</tr>
		
		<tr class="prop">
			<td valign="top" class="name"><g:message code="productCategory.products.label" default="Products" /></td>
			
			<td valign="top" style="text-align: left;" class="value">
				<ul>
					<g:each in="${productCategoryInstance.products}" var="p">
						<li><g:link controller="product" action="show" id="${p.id}">${p?.encodeAsHTML()}</g:link></li>
					</g:each>
				</ul>
			</td>
			
		</tr>
		
		</tbody>
	</table>
</section>

</body>

</html>